---
- name: Create system group
  group: name={{appGroup}} state=present system=yes

- name: Create application user
  user: name={{appUser}} comment=applicationUser group={{appGroup}}

- name: Create application user password
  user: name={{appUser}} password={{appPass}}

- name: Create Group Access dir
  file: path={{groupAccessPath}} state=directory owner={{appUser}} group={{appGroup}}

- name: Create Uwsgi dir
  file: path={{uwsgiDir}} state=directory

- name: Create Uwsgi deamon dir
  file: path={{uwsgiVassalsDir}} state=directory

- name: Create Uwsgi log dir
  file: path={{uwsgiLogDir}} state=directory owner={{appUser}} group={{appGroup}}

- name: Deploy app uwsgi ini file
  template: src=uwsgi.ini dest={{uwsgiVassalsDir}}

- name: Own uwsgi vassals dir
  file: path={{uwsgiVassalsDir}} state=directory owner={{appUser}} group={{appGroup}} mode=775 recurse=yes

- name: Install libpg-dev
  apt: pkg=libpq-dev state=present update_cache=true

- name: add repository and install its signing key
  shell: curl -sL https://deb.nodesource.com/setup_10.x | bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Install Python pip psycopg2
  apt: 
    pkg:
      - python3-psycopg2
      - python3-pip 
    state: present
    update_cache: yes

- name: Install node npm
  apt: 
    pkg:
      - nodejs 
    state: present
    update_cache: yes
 
- name: Install virtualenv package
  command: pip3 install virtualenv

- name: Install uwsgi package
  command: pip3 install uwsgi

- name: Install vue-cli package globally.
  npm:
    name: '@vue/cli'
    global: yes

- name: Install pm2 package globally.
  npm:
    name: pm2
    global: yes

- name: Setup Uwsgi service
  template: src=emperor.uwsgi.service dest=/etc/systemd/system/

- name: systemd deamon reload
  systemd: daemon_reload=yes

- name: enable the uwsgi service
  systemd:
    name: emperor.uwsgi.service
    state: started
    enabled: True
