---
- name: Create system group
  group: name={{appGroup}} state=present system=yes

- name: Create application user
  user: name={{appUser}} comment=applicationUser group={{appGroup}}

- name: Create application user password
  user: name={{appUser}} password={{appPass}}

- name: Create Group Access dir
  file: path={{groupAccessPath}} state=directory owner={{appUser}} group={{appGroup}}

- name: Create Uwsgi dir
  file: path={{uwsgiDir}} state=directory

- name: Create Uwsgi deamon dir
  file: path={{uwsgiVassalsDir}} state=directory

- name: Create Uwsgi log dir
  file: path={{uwsgiLogDir}} state=directory owner={{appUser}} group={{appGroup}}

- name: Deploy app uwsgi ini file
  template: src=uwsgi.ini dest={{uwsgiVassalsDir}}

- name: Own uwsgi vassals dir
  file: path={{uwsgiVassalsDir}} state=directory owner={{appUser}} group={{appGroup}} mode=775 recurse=yes

- name: Install libpg-dev
  apt: pkg=libpq-dev state=present update_cache=true

- name: Install Python pip  psycopg2
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - python-psycopg2 # Required for Ansible to interact with postgres
    - python3-pip
    - nodejs

- name: Install virtualenv package
  command: pip3 install virtualenv

- name: Install uwsgi package
  command: pip3 install uwsgi

- name: Setup Uwsgi service
  template: src=emperor.uwsgi.service dest=/etc/systemd/system/

- name: systemd deamon reload
  systemd: daemon_reload=yes

- name: enable the uwsgi service
  systemd:
    name: emperor.uwsgi.service
    state: started
    enabled: True
